{
 "title": "Sensor Readings by Sensor",
 "time": { "from": "2020-12-07T05:33:37.917Z", "to": "2020-12-11T05:33:37.921Z" },
 "panels": [
  {
   "title": "Water Level Both Tanks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Water Level" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  location AS metric,\n  valueraw AS \"Value\"\nFROM SensorData\nWHERE\n  sensor = 'optomax_SPI' \nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Left Closet Minimum Readings",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  sensor AS metric,\n  min(valueraw) AS \"valueraw\"\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  location = 'left_closet'\nGROUP BY 1,2\nORDER BY $__timeGroup(reading_time,$__interval)"
    }
   ]
  },
  {
   "title": "Right Closet Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  sensor AS metric,\n  valueraw\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  sensor = 'humidity' AND\n  location = 'right_closet'\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Left Closet Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) DIV 60 * 60 AS \"time\",\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  reading_time BETWEEN FROM_UNIXTIME(1607378346) AND FROM_UNIXTIME(1607464746) AND\n  sensor = 'pressure' AND location = 'left_closet'\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(reading_time) DIV 60 * 60"
    }
   ]
  },
  {
   "title": "Left Closet Max Readings",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  sensor AS metric,\n  max(valueraw) AS \"valueraw\"\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  location = 'left_closet'\nGROUP BY 1,2\nORDER BY $__timeGroup(reading_time,$__interval)"
    }
   ]
  },
  {
   "title": "Right Closet Submerged Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) DIV 60 * 60 AS \"time\",\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  reading_time BETWEEN FROM_UNIXTIME(1607378346) AND FROM_UNIXTIME(1607464746) AND\n  sensor = 'subm_temp' AND location = 'right_closet'\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(reading_time) DIV 60 * 60"
    }
   ]
  },
  {
   "title": "Left Closet Submerged Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) DIV 60 * 60 AS \"time\",\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  reading_time BETWEEN FROM_UNIXTIME(1607378346) AND FROM_UNIXTIME(1607464746) AND\n  sensor = 'subm_temp' AND location = 'left_closet'\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(reading_time) DIV 60 * 60"
    }
   ]
  },
  {
   "title": "Sensor Readings > 30 Days",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time)\nGROUP BY 1,2\nORDER BY $__timeGroup(reading_time,$__interval)"
    }
   ]
  },
  {
   "title": "Right Closet Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  location = 'right_closet' AND\n  sensor = 'humidity'\nGROUP BY 1,2\nORDER BY $__timeGroup(reading_time,$__interval)"
    }
   ]
  },
  {
   "title": "Left Closet Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) DIV 60 * 60 AS \"time\",\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  reading_time BETWEEN FROM_UNIXTIME(1607378346) AND FROM_UNIXTIME(1607464746) AND\n  sensor = 'humidity' AND location = 'left_closet'\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(reading_time) DIV 60 * 60"
    }
   ]
  },
  {
   "title": "Right Closet Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  location = 'right_closet' AND\n  sensor = 'temperature'\nGROUP BY 1,2\nORDER BY $__timeGroup(reading_time,$__interval)"
    }
   ]
  },
  {
   "title": "Left Closet Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  sensor AS metric,\n  avg(valueraw) AS \"valueraw\"\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  location = 'left_closet' AND\n  sensor = 'temperature'\nGROUP BY 1,2\nORDER BY $__timeGroup(reading_time,$__interval)"
    }
   ]
  },
  {
   "title": "Right Closet ORP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) DIV 60 * 60 AS \"time\",\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  reading_time BETWEEN FROM_UNIXTIME(1607378346) AND FROM_UNIXTIME(1607464746) AND\n  sensor = 'orp' AND location = 'right_closet'\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(reading_time) DIV 60 * 60"
    }
   ]
  },
  {
   "title": "Left Closet ORP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) DIV 60 * 60 AS \"time\",\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  reading_time BETWEEN FROM_UNIXTIME(1607378346) AND FROM_UNIXTIME(1607464746) AND\n  sensor = 'orp' AND location = 'left_closet'\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(reading_time) DIV 60 * 60"
    }
   ]
  },
  {
   "title": "Right Closet EC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) DIV 60 * 60 AS \"time\",\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  reading_time BETWEEN FROM_UNIXTIME(1607378346) AND FROM_UNIXTIME(1607464746) AND\n  sensor = 'ec' AND location = 'right_closet'\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(reading_time) DIV 60 * 60"
    }
   ]
  },
  {
   "title": "Left Closet EC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) DIV 60 * 60 AS \"time\",\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  reading_time BETWEEN FROM_UNIXTIME(1607378346) AND FROM_UNIXTIME(1607464746) AND\n  sensor = 'ec' AND location = 'left_closet'\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(reading_time) DIV 60 * 60"
    }
   ]
  },
  {
   "title": "Right Closet pH",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Volume" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  sensor = 'ph' AND location = 'right_closet'\nGROUP BY 1,2\nORDER BY $__timeGroup(reading_time,$__interval)"
    }
   ]
  },
  {
   "title": "Left Closet pH",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(reading_time,$__interval),\n  sensor AS metric,\n  avg(valueraw) AS \"Value\"\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  sensor = 'ph' AND location = 'left_closet'\nGROUP BY 1,2\nORDER BY $__timeGroup(reading_time,$__interval)"
    }
   ]
  }
 ]
}